name: Python Application CI

# Define the permissions for this workflow
permissions:
  contents: read  # Read access to the repository contents
  pull-requests: write  # Write access for pull requests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies in virtual environment
      run: |
        python -m venv .venv
        .venv/bin/python -m pip install --upgrade pip
        .venv/bin/python -m pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m venv .venv
        .venv/bin/python -m unittest discover -s tests
        